# https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-composite-run-steps-action
name: .Net Playground
description: A .Net Playground
inputs:
  version:
    description: Version to install
    required: true
runs:
  using: composite
  steps:
  - run: |
      dotnet tool install --global Octopus.DotNet.Cli --version ${{ inputs.version }}
    shell: bash
  - run: |
      mkdir -p "$HOME/.dotnet-octo/bin"
      cp ./octo "$HOME/.dotnet-octo/bin"
      echo "$HOME/.dotnet-octo/bin" >> $GITHUB_PATH
    shell: bash
