name: dotnet playground

on:
  push:

jobs:
  dotnet-playground:
    name: dotnet playground
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, windows-2016, ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2

    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: 3.1.x

    - name: Install Octopus CLI
      uses: ./
      with:
        version: 7.4.2

    # - name: Run Octopus CLI
    #   run: |
    #     octo version
